
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sarah
 */
public class AdmAllaProjekt extends javax.swing.JFrame {
    
    private String epost;

    /**
     * Creates new form AdmAllaProjekt
     */
    public AdmAllaProjekt(String e) {
        initComponents();
        epost = e;
        fyllcbxUtbildningsprojekt();
        fyllcbxForskningsprojekt();
    }
    
    private void fyllcbxUtbildningsprojekt() {
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        PreparedStatement ps = null;
        String inlagg = null;
        cbxUtbildningsprojekt.addItem("");

        try {
            String fraga = "SELECT TITEL FROM UTBILDNINGSPROJEKT";
            ps = connection.prepareStatement(fraga);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                inlagg = rs.getString(1);
                cbxUtbildningsprojekt.addItem(inlagg);
            }
        } catch (Exception e) {
            System.out.println("Felmeddelande! " + e);
        }
    }
    
    private void fyllcbxForskningsprojekt() {
         DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        PreparedStatement ps = null;
        String inlagg = null;
        cbxForskningsprojekt.addItem("");

        try {
            String fraga = "SELECT TITEL FROM FORSKNINGSPROJEKT";
            ps = connection.prepareStatement(fraga);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                inlagg = rs.getString(1);
                cbxForskningsprojekt.addItem(inlagg);
            }
        } catch (Exception e) {
            System.out.println("Felmeddelande! " + e);
        }
    }
    
    private void updateSql(String statement)
    {
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        try{
       PreparedStatement ps = connection.prepareStatement(statement);
       ps.executeUpdate();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAllaProjekt = new javax.swing.JLabel();
        lblUtbprojekt = new javax.swing.JLabel();
        btnRadera = new javax.swing.JButton();
        btnAvbryt = new javax.swing.JButton();
        lblForskningsprojekt = new javax.swing.JLabel();
        cbxUtbildningsprojekt = new javax.swing.JComboBox<>();
        cbxForskningsprojekt = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAllaProjekt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblAllaProjekt.setText("Alla projekt");

        lblUtbprojekt.setText("Välj utbildningsprojekt:");

        btnRadera.setText("Radera");
        btnRadera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaderaActionPerformed(evt);
            }
        });

        btnAvbryt.setText("Avbryt");
        btnAvbryt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvbrytActionPerformed(evt);
            }
        });

        lblForskningsprojekt.setText("Välj forskningsprojekt:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUtbprojekt)
                            .addComponent(lblForskningsprojekt))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxUtbildningsprojekt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxForskningsprojekt, 0, 147, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(lblAllaProjekt)))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAvbryt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRadera, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblAllaProjekt)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUtbprojekt)
                    .addComponent(cbxUtbildningsprojekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblForskningsprojekt)
                    .addComponent(cbxForskningsprojekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnRadera, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnAvbryt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvbrytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvbrytActionPerformed
        this.dispose();
        new AnvStartsida(epost).setVisible(true);
    }//GEN-LAST:event_btnAvbrytActionPerformed

    private void btnRaderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaderaActionPerformed
       DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        PreparedStatement ps = null;


            String utbildningsTitel = cbxUtbildningsprojekt.getSelectedItem().toString();
            String forskningsTitel = cbxForskningsprojekt.getSelectedItem().toString();

            if (utbildningsTitel != null && forskningsTitel.equals("")) {

                String sql = "DELETE FROM UTBILDNINGSPROJEKT WHERE TITEL = '" + utbildningsTitel + "'";
                updateSql(sql);

                JOptionPane.showMessageDialog(null, "Projektet har raderats!");
                
            } else if (forskningsTitel != null && utbildningsTitel.equals("")) {
                String sql2 = "DELETE FROM FORSKNINGSPROJEKT WHERE TITEL = '" + forskningsTitel + "'";
                updateSql(sql2);

                JOptionPane.showMessageDialog(null, "Projektet har raderats!");

            } else if (utbildningsTitel != null && forskningsTitel != null) {
                JOptionPane.showMessageDialog(null, "Välj endast ett projekt!");
            }
            
    }//GEN-LAST:event_btnRaderaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvbryt;
    private javax.swing.JButton btnRadera;
    private javax.swing.JComboBox<String> cbxForskningsprojekt;
    private javax.swing.JComboBox<String> cbxUtbildningsprojekt;
    private javax.swing.JLabel lblAllaProjekt;
    private javax.swing.JLabel lblForskningsprojekt;
    private javax.swing.JLabel lblUtbprojekt;
    // End of variables declaration//GEN-END:variables
}
