
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sarah
 */
public class AdmAllaProjekt extends javax.swing.JFrame {

    private String epost;

    /**
     * Creates new form AdmAllaProjekt
     */
    public AdmAllaProjekt(String e) {
        initComponents();
        epost = e;
        fyllcbxUtbildningsprojekt();
        fyllcbxForskningsprojekt();
    }

    private void fyllcbxUtbildningsprojekt() {
        cbxUtbildning.removeAllItems();
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        PreparedStatement ps = null;
        String inlagg = null;
        cbxUtbildning.addItem("");

        try {
            String fraga = "SELECT TITEL FROM UTBILDNINGSPROJEKT";
            ps = connection.prepareStatement(fraga);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                inlagg = rs.getString(1);
                cbxUtbildning.addItem(inlagg);
            }
        } catch (Exception e) {
            System.out.println("Felmeddelande! " + e);
        }
    }

    private void fyllcbxForskningsprojekt() {
        cbxForskning.removeAllItems();
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        PreparedStatement ps = null;
        String inlagg = null;
        cbxForskning.addItem("");

        try {
            String fraga = "SELECT TITEL FROM FORSKNINGSPROJEKT";
            ps = connection.prepareStatement(fraga);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                inlagg = rs.getString(1);
                cbxForskning.addItem(inlagg);
            }
        } catch (Exception e) {
            System.out.println("Felmeddelande! " + e);
        }
    }

    private void updateSql(String statement) {
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        try {
            PreparedStatement ps = connection.prepareStatement(statement);
            ps.executeUpdate();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAllaProjekt = new javax.swing.JLabel();
        lblUtbprojekt = new javax.swing.JLabel();
        btnRadera = new javax.swing.JButton();
        btnAvbryt = new javax.swing.JButton();
        lblForskningsprojekt = new javax.swing.JLabel();
        cbxUtbildning = new javax.swing.JComboBox<>();
        cbxForskning = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAllaProjekt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblAllaProjekt.setText("Alla projekt");

        lblUtbprojekt.setText("Välj utbildningsprojekt:");

        btnRadera.setText("Radera");
        btnRadera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaderaActionPerformed(evt);
            }
        });

        btnAvbryt.setText("Tillbaka");
        btnAvbryt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvbrytActionPerformed(evt);
            }
        });

        lblForskningsprojekt.setText("Välj forskningsprojekt:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUtbprojekt)
                            .addComponent(lblForskningsprojekt))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxUtbildning, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxForskning, 0, 147, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(lblAllaProjekt)))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAvbryt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRadera, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblAllaProjekt)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUtbprojekt)
                    .addComponent(cbxUtbildning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblForskningsprojekt)
                    .addComponent(cbxForskning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnRadera, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnAvbryt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvbrytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvbrytActionPerformed
        this.dispose();
        new AnvStartsida(epost).setVisible(true);
    }//GEN-LAST:event_btnAvbrytActionPerformed

    private void btnRaderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaderaActionPerformed
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        PreparedStatement ps = null;

        String utbildningsTitel = cbxUtbildning.getSelectedItem().toString();
        String forskningsTitel = cbxForskning.getSelectedItem().toString();
        if (utbildningsTitel.equals("") && forskningsTitel.equals("")) {
            JOptionPane.showMessageDialog(null, "Välj ett projekt!");
        } else if (utbildningsTitel != null && forskningsTitel.equals("")) {
            String uPid = getUFpid("SELECT UPID FROM UTBILDNINGSPROJEKT WHERE TITEL = '" + utbildningsTitel + "'");
            String sql1 = "DELETE FROM UTBILDNINGSPROJEKT WHERE UPID =" + uPid;
            String sql2 = "DELETE FROM UTBILDNINGSINLAGG WHERE UPID =" + uPid;
            String sql3 = "DELETE FROM ANVANDARE_UTBILDNINGSPROJEKT WHERE UPID =" + uPid;
            updateSql(sql3);
            updateSql(sql2);
            updateSql(sql1);

            JOptionPane.showMessageDialog(null, "Projektet har raderats!");

            fyllcbxUtbildningsprojekt();
        } else if (forskningsTitel != null && utbildningsTitel.equals("")) {
            String fPid = getUFpid("SELECT FPID FROM FORSKNINGSPROJEKT WHERE TITEL = '" + forskningsTitel + "'");
            String sql1 = "DELETE FROM FORSKNINGSPROJEKT WHERE FPID =" + fPid;
            String sql2 = "DELETE FROM FORSKNINGSINLAGG WHERE FPID =" + fPid;
            String sql3 = "DELETE FROM ANVANDARE_FORSKNINGSPROJEKT WHERE FPID =" + fPid;
            updateSql(sql3);
            updateSql(sql2);
            updateSql(sql1);

            JOptionPane.showMessageDialog(null, "Projektet har raderats!");

            fyllcbxForskningsprojekt();
        } else if (utbildningsTitel != null && forskningsTitel != null) {
            JOptionPane.showMessageDialog(null, "Välj endast ett projekt!");
        }

    }//GEN-LAST:event_btnRaderaActionPerformed

    private String getUFpid(String q) {
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        String svar = null;
        try {
            PreparedStatement ps = connection.prepareStatement(q);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                svar = rs.getString(1);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return svar;
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvbryt;
    private javax.swing.JButton btnRadera;
    private javax.swing.JComboBox<String> cbxForskning;
    private javax.swing.JComboBox<String> cbxUtbildning;
    private javax.swing.JLabel lblAllaProjekt;
    private javax.swing.JLabel lblForskningsprojekt;
    private javax.swing.JLabel lblUtbprojekt;
    // End of variables declaration//GEN-END:variables
}
