
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author martinnoe
 */
public class AnvStartsida extends javax.swing.JFrame {

    private String epost;

    /**
     * Creates new form AnvStartsida
     */
    public AnvStartsida() {
        initComponents();
        this.setLocationRelativeTo(null);
        kollaAdmin();
    }
    
    public AnvStartsida(String e){
        epost = e;
        initComponents();
        this.setLocationRelativeTo(null);
        kollaAdmin();
    }
    
    //Kollar om användaren är admin och sätter vissa knappar synliga i sådana fall
    public void kollaAdmin()
    {
        try
        {
        String fraga = "SELECT ADMIN FROM ANVANDARE WHERE EPOST = '" + epost + "'"; 
        String svar = getQuery(fraga);
        
        if(svar.equals("T"))
        {
        btnAdmProfiler.setVisible(true);
        btnAdmSkapaAnv.setVisible(true);
        }
        else
        {
        btnAdmProfiler.setVisible(false);
        btnAdmSkapaAnv.setVisible(false);
        }
        
        }
        catch(Exception ex){
        JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }

    
        public String getQuery(String q){
        String svar = null;
        DB_connection.DB_Connection obj_DB_Connection= new DB_connection.DB_Connection();
	Connection connection=obj_DB_Connection.get_connection();
	PreparedStatement ps=null;
	try {
	    String query= q;
	    ps=connection.prepareStatement(query);
	    ResultSet rs=ps.executeQuery();
	    while(rs.next()){
                svar = rs.getString(1);
	    }
	} catch (Exception e) {
	    System.out.println(e);
	} 
        return svar;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSeFormellBlogg = new javax.swing.JButton();
        btnSeInformellBlogg = new javax.swing.JButton();
        btnSeInlägg = new javax.swing.JButton();
        btnSeProfil = new javax.swing.JButton();
        btnLoggaUt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAdmProfiler = new javax.swing.JButton();
        btnAdmSkapaAnv = new javax.swing.JButton();
        btnForskningsProjekt = new javax.swing.JButton();
        btnUtbildningsProjekt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSeFormellBlogg.setText("Formell Blogg");
        btnSeFormellBlogg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeFormellBloggActionPerformed(evt);
            }
        });

        btnSeInformellBlogg.setText("Informell Blogg");
        btnSeInformellBlogg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeInformellBloggActionPerformed(evt);
            }
        });

        btnSeInlägg.setText("Mina inlägg");
        btnSeInlägg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeInläggActionPerformed(evt);
            }
        });

        btnSeProfil.setText("Min profilsida");
        btnSeProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeProfilActionPerformed(evt);
            }
        });

        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setText("Välkommen till din sida!");

        btnAdmProfiler.setText("Hantera användare");
        btnAdmProfiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmProfilerActionPerformed(evt);
            }
        });

        btnAdmSkapaAnv.setText("Skapa användare");
        btnAdmSkapaAnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmSkapaAnvActionPerformed(evt);
            }
        });

        btnForskningsProjekt.setText("Forskningsprojekt");
        btnForskningsProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForskningsProjektActionPerformed(evt);
            }
        });

        btnUtbildningsProjekt.setText("Utbildningsprojekt");
        btnUtbildningsProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtbildningsProjektActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLoggaUt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUtbildningsProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(btnForskningsProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSeInformellBlogg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSeFormellBlogg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdmSkapaAnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSeInlägg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSeProfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdmProfiler, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                        .addGap(122, 122, 122)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeFormellBlogg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeInformellBlogg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeInlägg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnForskningsProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdmSkapaAnv, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUtbildningsProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdmProfiler, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(btnLoggaUt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeProfilActionPerformed
            this.dispose();
        new ProfilSida(epost).setVisible(true);
    }//GEN-LAST:event_btnSeProfilActionPerformed

    private void btnSeFormellBloggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeFormellBloggActionPerformed
        this.dispose();
        new FormellBlogg(epost).setVisible(true);
    }//GEN-LAST:event_btnSeFormellBloggActionPerformed

    private void btnSeInformellBloggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeInformellBloggActionPerformed
        this.dispose();
        //new InformellBlogg(epost).setVisible(true);
        new bloggExperiment(epost).setVisible(true);

    }//GEN-LAST:event_btnSeInformellBloggActionPerformed

    private void btnSeInläggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeInläggActionPerformed
        this.dispose();
        new MinaInlagg(epost).setVisible(true);
    }//GEN-LAST:event_btnSeInläggActionPerformed

    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
       this.dispose();
       new Inlogg().setVisible(true);
    }//GEN-LAST:event_btnLoggaUtActionPerformed

    private void btnAdmProfilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmProfilerActionPerformed
        this.dispose();
        new hanteraAnvandare(epost).setVisible(true);
    }//GEN-LAST:event_btnAdmProfilerActionPerformed

    private void btnAdmSkapaAnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmSkapaAnvActionPerformed
        this.dispose();
        new skapaAnvandare(epost).setVisible(true);
    }//GEN-LAST:event_btnAdmSkapaAnvActionPerformed

    private void btnForskningsProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForskningsProjektActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnForskningsProjektActionPerformed

    private void btnUtbildningsProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtbildningsProjektActionPerformed
        this.dispose();
        new UtbildningsProjekt(epost).setVisible(true);
    }//GEN-LAST:event_btnUtbildningsProjektActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmProfiler;
    private javax.swing.JButton btnAdmSkapaAnv;
    private javax.swing.JButton btnForskningsProjekt;
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JButton btnSeFormellBlogg;
    private javax.swing.JButton btnSeInformellBlogg;
    private javax.swing.JButton btnSeInlägg;
    private javax.swing.JButton btnSeProfil;
    private javax.swing.JButton btnUtbildningsProjekt;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
