
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author martinnoe
 */
public class AnvStartsida extends javax.swing.JFrame {

    private String epost;

    /**
     * Creates new form AnvStartsida
     */
    public AnvStartsida() {
        initComponents();
        this.setLocationRelativeTo(null);
        kollaAdmin();
    }
    
    public AnvStartsida(String e){
        epost = e;
        initComponents();
        this.setLocationRelativeTo(null);
        kollaAdmin();
    }
    
    //Kollar om användaren är admin och sätter vissa knappar synliga i sådana fall
    public void kollaAdmin()
    {
        try
        {
        String fraga = "SELECT ADMIN FROM ANVANDARE WHERE EPOST = '" + epost + "'"; 
        String svar = getQuery(fraga);
        
        if(svar.equals("T"))
        {
        btnAdmProfiler.setVisible(true);
        }
        else
        {
        btnAdmProfiler.setVisible(false);
        }
        
        }
        catch(Exception ex){
        JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }

    
        public String getQuery(String q){
        String svar = null;
        DB_connection.DB_Connection obj_DB_Connection= new DB_connection.DB_Connection();
	Connection connection=obj_DB_Connection.get_connection();
	PreparedStatement ps=null;
	try {
	    String query= q;
	    ps=connection.prepareStatement(query);
	    ResultSet rs=ps.executeQuery();
	    while(rs.next()){
                svar = rs.getString(1);
	    }
	} catch (Exception e) {
	    System.out.println(e);
	} 
        return svar;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSeFormellBlogg = new javax.swing.JButton();
        btnSeInformellBlogg = new javax.swing.JButton();
        btnSeInlägg = new javax.swing.JButton();
        btnSeProfil = new javax.swing.JButton();
        btnLoggaUt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAdmProfiler = new javax.swing.JButton();
        btnAdmSkapaAnv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSeFormellBlogg.setText("Formell Blogg");
        btnSeFormellBlogg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeFormellBloggActionPerformed(evt);
            }
        });

        btnSeInformellBlogg.setText("Informell Blogg");
        btnSeInformellBlogg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeInformellBloggActionPerformed(evt);
            }
        });

        btnSeInlägg.setText("Se mina inlägg");
        btnSeInlägg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeInläggActionPerformed(evt);
            }
        });

        btnSeProfil.setText("Se min profilsida");
        btnSeProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeProfilActionPerformed(evt);
            }
        });

        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Välkommen till din sida!");

        btnAdmProfiler.setText("Hantera profiler");
        btnAdmProfiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmProfilerActionPerformed(evt);
            }
        });

        btnAdmSkapaAnv.setText("Skapa användare");
        btnAdmSkapaAnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmSkapaAnvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSeFormellBlogg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSeProfil)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSeInformellBlogg)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLoggaUt))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAdmSkapaAnv)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(btnSeInlägg)
                                    .addGap(263, 263, 263)
                                    .addComponent(btnAdmProfiler))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(144, 144, 144)
                                    .addComponent(jLabel1))))
                        .addGap(0, 47, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeFormellBlogg)
                    .addComponent(btnSeProfil))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeInformellBlogg)
                    .addComponent(btnAdmSkapaAnv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeInlägg)
                    .addComponent(btnAdmProfiler))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(btnLoggaUt)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeProfilActionPerformed
            this.dispose();
        new ProfilSida(epost).setVisible(true);
    }//GEN-LAST:event_btnSeProfilActionPerformed

    private void btnSeFormellBloggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeFormellBloggActionPerformed
        this.dispose();
        new FormellBlogg(epost).setVisible(true);
    }//GEN-LAST:event_btnSeFormellBloggActionPerformed

    private void btnSeInformellBloggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeInformellBloggActionPerformed
        this.dispose();
        new InformellBlogg().setVisible(true);
    }//GEN-LAST:event_btnSeInformellBloggActionPerformed

    private void btnSeInläggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeInläggActionPerformed
        this.dispose();
        new MinaInlagg().setVisible(true);
    }//GEN-LAST:event_btnSeInläggActionPerformed

    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
       this.dispose();
       new Inlogg().setVisible(true);
    }//GEN-LAST:event_btnLoggaUtActionPerformed

    private void btnAdmProfilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmProfilerActionPerformed
        this.dispose();
        new hanteraAnvandare(epost).setVisible(true);
    }//GEN-LAST:event_btnAdmProfilerActionPerformed

    private void btnAdmSkapaAnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmSkapaAnvActionPerformed
        this.dispose();
        new skapaAnvandare(epost).setVisible(true);
    }//GEN-LAST:event_btnAdmSkapaAnvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmProfiler;
    private javax.swing.JButton btnAdmSkapaAnv;
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JButton btnSeFormellBlogg;
    private javax.swing.JButton btnSeInformellBlogg;
    private javax.swing.JButton btnSeInlägg;
    private javax.swing.JButton btnSeProfil;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
