
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sarah
 */
public class ForskningsProjekt extends javax.swing.JFrame {
    
    private String epost;
    private String id; 
    String filepath;
    private byte[] filebytes;
    /**
     * Creates new sform ForskningsProjekt
     */
    public ForskningsProjekt(String e) {
        initComponents();
        this.setLocationRelativeTo(null);
        epost = e;
        id = getId();
        fillBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblForskningsProjekt = new javax.swing.JLabel();
        lblProjektAtkomst = new javax.swing.JLabel();
        cbxProjekt = new javax.swing.JComboBox<>();
        btnVisaProjekt = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblSkrivInlagg = new javax.swing.JLabel();
        lblRubrik = new javax.swing.JLabel();
        txfRubrik = new javax.swing.JTextField();
        lblText = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaText = new javax.swing.JTextArea();
        lblFil = new javax.swing.JLabel();
        txfLaddaUppFil = new javax.swing.JTextField();
        btnValjFil = new javax.swing.JButton();
        btnPosta = new javax.swing.JButton();
        btnMinaProjekt = new javax.swing.JButton();
        btnSkapaNyttProjekt = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblInlagg = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtInlagg = new javax.swing.JTextArea();
        txtSokvag = new javax.swing.JTextField();
        btnOppnaFil = new javax.swing.JButton();
        lblInlaggRubrik = new javax.swing.JLabel();
        lblForfattare = new javax.swing.JLabel();
        lblTidpunkt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblForskningsProjekt.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblForskningsProjekt.setText("Forskningsprojekt");

        lblProjektAtkomst.setText("Projekt jag har åtkomst till:");

        btnVisaProjekt.setText("Visa");
        btnVisaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaProjektActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lblSkrivInlagg.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblSkrivInlagg.setText("Skriv ett inlägg i projektet!");

        lblRubrik.setText("Rubrik:");

        lblText.setText("Text:");

        txaText.setColumns(20);
        txaText.setRows(5);
        jScrollPane2.setViewportView(txaText);

        lblFil.setText("Ladda upp fil:");

        btnValjFil.setText("Välj");
        btnValjFil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValjFilActionPerformed(evt);
            }
        });

        btnPosta.setText("Publicera");
        btnPosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblRubrik))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblText))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFil)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txfLaddaUppFil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnValjFil))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(txfRubrik))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 128, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSkrivInlagg)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPosta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSkrivInlagg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRubrik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(lblFil))
                            .addComponent(lblText)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txfRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfLaddaUppFil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnValjFil))))
                .addGap(18, 18, 18)
                .addComponent(btnPosta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        btnMinaProjekt.setText("Mina projekt");
        btnMinaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinaProjektActionPerformed(evt);
            }
        });

        btnSkapaNyttProjekt.setText("Skapa nytt projekt");
        btnSkapaNyttProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaNyttProjektActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");

        tblInlagg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rubrik", "Författare"
            }
        ));
        tblInlagg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInlaggMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblInlagg);

        txtInlagg.setColumns(20);
        txtInlagg.setRows(5);
        jScrollPane4.setViewportView(txtInlagg);

        btnOppnaFil.setText("Öppna");
        btnOppnaFil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOppnaFilActionPerformed(evt);
            }
        });

        jLabel2.setText("Välj ett inlägg att visa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblForskningsProjekt)
                .addGap(339, 339, 339))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(lblInlaggRubrik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(txtSokvag)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnOppnaFil, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblForfattare, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(lblTidpunkt, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(270, 270, 270)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnMinaProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSkapaNyttProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblProjektAtkomst)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnVisaProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblForskningsProjekt)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProjektAtkomst)
                            .addComponent(cbxProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVisaProjekt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMinaProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSkapaNyttProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblInlaggRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblForfattare, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTidpunkt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSokvag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOppnaFil)
                            .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaProjektActionPerformed
        this.dispose();
        new MinaProjekt(epost,id,false).setVisible(true);
    }//GEN-LAST:event_btnMinaProjektActionPerformed

    private void btnSkapaNyttProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaNyttProjektActionPerformed
        this.dispose();
        new SkapaNyttForskningsProjekt(epost).setVisible(true);
        
    }//GEN-LAST:event_btnSkapaNyttProjektActionPerformed

    private void btnPostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostaActionPerformed
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        PreparedStatement ps = null;
        if (Validering.textFaltHarVarde(txfRubrik) && Validering.textAreaHarVarde(txaText))
        {
            try
            {
            String sokväg = null;
            byte[] fileBytes = null;
                    
                    if (txfLaddaUppFil.getText().isEmpty()) 
                    {
                        //String sokväg = null;
                    }
                    else
                    {
                        sokväg = txfLaddaUppFil.getText();
                        Path path = Paths.get(sokväg);
                        fileBytes = Files.readAllBytes(path);
                        sokväg = path.getFileName().toString();
                    }

            //String sokväg = txfLaddaUppFil.getText();
            //Path path = Paths.get(sokväg);
            //byte[] fileBytes = Files.readAllBytes(path);
            
            String rubrik = txfRubrik.getText();
            String text = txaText.getText();
            String fiid = GetAutoId("SELECT MAX(FIID) FROM FORSKNINGSINLAGG");
            String tidpunkt = hemtaTidpunkt();
            String personId = getId();
            String fpid = getFpid();
            
            //sokväg = path.getFileName().toString();

//            String query = "INSERT INTO FORSKNINGSINLAGG VALUES ("+fiid+",'"+rubrik+"','"+text+"','"sokväg"','"+tidpunkt+"',"+personId+","+fpid+","fileBytes")";
            String query = "insert into FORSKNINGSINLAGG (FIID, RUBRIK, TEXT, TIDPUNKT, ANVANDARID, FPID, NYFIL, FIL) values"
                        + " (?, ?, ?, ?, ?, ?, ?, ?)";
                ps = connection.prepareStatement(query);
                ps.setString(1, fiid);
                ps.setString(2, rubrik);
                ps.setString(3, text);                         
                ps.setString(4, tidpunkt);
                ps.setString(5, personId);
                ps.setString(6, fpid);
                ps.setBytes(7, fileBytes);
                ps.setString(8, sokväg); 
                ps.execute();
            updateSql(query);
            JOptionPane.showMessageDialog(null, "Inlägget har publicerats!");
            txfRubrik.setText(null);
            txaText.setText(null);
            
        }
            
       catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btnPostaActionPerformed

    private void btnValjFilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValjFilActionPerformed
        // TODO add your handling code here:
      JFileChooser jfc = new JFileChooser();
      jfc.showOpenDialog(this);
      
      try {
                  File f = jfc.getSelectedFile();
                  filepath = f.getAbsolutePath();
                  
                  
                  filepath = filepath.replace('\\', '/');
                  txfLaddaUppFil.setText(filepath);
//                  Path path = Paths.get(filepath);
//                  byte[] fileBytes = Files.readAllBytes(path);
      }
      catch (Exception e)
      {
          JOptionPane.showMessageDialog(rootPane, e);
      }
    }//GEN-LAST:event_btnValjFilActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        this.dispose();
        new AnvStartsida(epost).setVisible(true);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void tblInlaggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInlaggMouseClicked

        DefaultTableModel tabellen = (DefaultTableModel)tblInlagg.getModel();
        int selectedRowIndex = tblInlagg.getSelectedRow();

        String id = (tabellen.getValueAt(selectedRowIndex, 0).toString());
        

        //id är rubrik nu dock

        String fraga= "SELECT * FROM FORSKNINGSINLAGG WHERE RUBRIK = '" + id + "'";

        String text = GetText(fraga);
          
    }//GEN-LAST:event_tblInlaggMouseClicked

    public String GetText(String s)
    {
	DB_connection.DB_Connection obj_DB_Connection= new DB_connection.DB_Connection();
	Connection connection=obj_DB_Connection.get_connection();
	PreparedStatement ps=null;
        String rubrik = null;
        String text = null;
        String tidpunkt = null;
        String fil = null;
        

	try {
	    String query= s;
	    ps=connection.prepareStatement(query);
	    ResultSet rs=ps.executeQuery();
	    while(rs.next()){
                rubrik = rs.getString(2);
                text = rs.getString(3);
                tidpunkt = rs.getString(4);
                filebytes = rs.getBytes(7);
                fil = rs.getString(8);
                
	    }
            DefaultTableModel tabellen = (DefaultTableModel)tblInlagg.getModel();
            int selectedRowIndex = tblInlagg.getSelectedRow();
            
            String namn = "Av: " + (tabellen.getValueAt(selectedRowIndex, 1).toString());
            
            String tid = tidpunkt.substring(0, 16);
            
            lblInlaggRubrik.setText(rubrik);
            txtInlagg.setText(text);    
            lblForfattare.setText(namn);            
            lblTidpunkt.setText(tid);
            txtSokvag.setText(fil);
            
            
	} catch (Exception e) {
	    System.out.println(e);
	}         
        
        return text;
    }
    
    public String GetQuery(String s)
    {
	DB_connection.DB_Connection obj_DB_Connection= new DB_connection.DB_Connection();
	Connection connection=obj_DB_Connection.get_connection();
	PreparedStatement ps=null;
        String rubrik = null;
        String fornamn = null;
        String efternamn = null;
        
        DefaultTableModel tabellen = (DefaultTableModel)tblInlagg.getModel();
        int rowCount = tabellen.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            tabellen.removeRow(i);
        }
        
	try {
	    String query= s;
	    ps=connection.prepareStatement(query);
	    ResultSet rs=ps.executeQuery();
	    while(rs.next()){
                rubrik = rs.getString(2);
                fornamn = rs.getString(10);
                efternamn = rs.getString(11);
                
                String forfattare = fornamn + " " + efternamn;
                                                
                DefaultTableModel tabellen1 = (DefaultTableModel) tblInlagg.getModel();
                tabellen1.addRow(new Object[]{rubrik,forfattare});
                
                
	    }
	} catch (Exception e) {
	    System.out.println(e);
	} 
        return rubrik;
    }
    private void btnVisaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaProjektActionPerformed
        String rubrik = cbxProjekt.getSelectedItem().toString();
        
        
            try
            {
            
            String fraga= "SELECT * FROM FORSKNINGSINLAGG JOIN ANVANDARE ON ANVANDARE.ANVANDARID = FORSKNINGSINLAGG.ANVANDARID JOIN FORSKNINGSPROJEKT ON FORSKNINGSINLAGG.FPID = FORSKNINGSPROJEKT.FPID WHERE FORSKNINGSPROJEKT.TITEL = '" + rubrik + "' ORDER BY TIDPUNKT DESC";
                
                
            String hemta = GetQuery(fraga);
                
                
            }
            catch (Exception bla)
            {
             JOptionPane.showMessageDialog(null, "Något gick fel!");
            }
            
        lblInlaggRubrik.setText("");
        txtInlagg.setText("");
        lblForfattare.setText("");
        lblTidpunkt.setText("");    
    }//GEN-LAST:event_btnVisaProjektActionPerformed

    private void btnOppnaFilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOppnaFilActionPerformed
        filepath = txtSokvag.getText();
        try {
            
           String basepath = System.getProperty("user.dir");
           String newfilepath = basepath + "\\src\\UploadedFiles\\" + filepath; 
           Path path = Paths.get(newfilepath);
           if (Files.exists(path))
                   {
                       Files.delete(path);
                   }
           File file = new File(newfilepath);
           FileOutputStream os = new FileOutputStream(file); 
           
           os.write(filebytes);
           os.close();
            
            File pdfFile = new File(newfilepath);
            if (pdfFile.exists())
            {
                if (Desktop.isDesktopSupported())
                {
                    Desktop.getDesktop().open(pdfFile);
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "desktop is not supported");
                }
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "File doesnt exist");
            }
        }
        catch ( HeadlessException | IOException e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }//GEN-LAST:event_btnOppnaFilActionPerformed
    }
        private String getId(){
        String id = null;
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        PreparedStatement ps = null;
        try {
            String query = "SELECT ANVANDARID FROM ANVANDARE WHERE EPOST='"+epost+"'";
            ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                id = rs.getString(1);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return id;
    }
        
     private void fillBox(){
        cbxProjekt.removeAllItems();
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        try {
            String query = "SELECT TITEL FROM ANVANDARE_FORSKNINGSPROJEKT JOIN FORSKNINGSPROJEKT ON ANVANDARE_FORSKNINGSPROJEKT.FPID=FORSKNINGSPROJEKT.FPID WHERE ANVANDARE_FORSKNINGSPROJEKT.ANVANDARID="+id;
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                cbxProjekt.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    public String GetAutoId(String o) {
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        int idNy = 1;
        try {
            String query = o;
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                idNy = rs.getInt(1);
            }

        } catch (Exception ex) {
            System.out.println("Internt felmeddelande: " + ex);
        }

        idNy = idNy + 1;

        return Integer.toString(idNy);

    }
    
    public String hemtaTidpunkt() {

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();

        return dtf.format(now);

    }
    
    public String getFpid(){
        int fPid = 0;
        String titel = cbxProjekt.getSelectedItem().toString();
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        try {
            PreparedStatement ps = connection.prepareStatement("SELECT FPID FROM FORSKNINGSPROJEKT WHERE TITEL ='"+titel+"'");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                fPid = rs.getInt(1);

            }

        } catch (Exception ex) {
            System.out.println("Internt felmeddelande: " + ex);
        }
        
        return Integer.toString(fPid);
        
    }
    
        private void updateSql(String statement)
    {
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        try{
       PreparedStatement ps = connection.prepareStatement(statement);
       ps.executeUpdate();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMinaProjekt;
    private javax.swing.JButton btnOppnaFil;
    private javax.swing.JButton btnPosta;
    private javax.swing.JButton btnSkapaNyttProjekt;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JButton btnValjFil;
    private javax.swing.JButton btnVisaProjekt;
    private javax.swing.JComboBox<String> cbxProjekt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblFil;
    private javax.swing.JLabel lblForfattare;
    private javax.swing.JLabel lblForskningsProjekt;
    private javax.swing.JLabel lblInlaggRubrik;
    private javax.swing.JLabel lblProjektAtkomst;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblSkrivInlagg;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblTidpunkt;
    private javax.swing.JTable tblInlagg;
    private javax.swing.JTextArea txaText;
    private javax.swing.JTextField txfLaddaUppFil;
    private javax.swing.JTextField txfRubrik;
    private javax.swing.JTextArea txtInlagg;
    private javax.swing.JTextField txtSokvag;
    // End of variables declaration//GEN-END:variables
}
