
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jenni
 */
public class MinaProjekt extends javax.swing.JFrame {

    private String epost;
    /**
     * Creates new form MinaProjekt
     */
    public MinaProjekt(String e) {
        initComponents();
        epost = e;
        fyllcbxUtbildning();
        fyllcbxForskning();
    }
    
    private void fyllcbxUtbildning() {
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        PreparedStatement ps = null;
        String inlagg = null;
        cbxUtbildning.addItem("");

        try {
            String fraga = "SELECT TITEL FROM UTBILDNINGSPROJEKT JOIN ANVANDARE ON UTBILDNINGSPROJEKT.ANVANDARID = ANVANDARE.ANVANDARID WHERE ANVANDARE.EPOST = '" + epost + "'";
            ps = connection.prepareStatement(fraga);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                inlagg = rs.getString(1);
                cbxUtbildning.addItem(inlagg);
            }
        } catch (Exception e) {
            System.out.println("Felmeddelande! " + e);
        }
    }
    
    private void fyllcbxForskning() {
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        PreparedStatement ps = null;
        String inlagg = null;
        cbxForskning.addItem("");

        try {
            String fraga = "SELECT TITEL FROM FORSKNINGSPROJEKT JOIN ANVANDARE ON FORSKNINGSPROJEKT.ANVANDARID = ANVANDARE.ANVANDARID WHERE ANVANDARE.EPOST = '" + epost + "'";
            ps = connection.prepareStatement(fraga);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                inlagg = rs.getString(1);
                cbxForskning.addItem(inlagg);
            }
        } catch (Exception e) {
            System.out.println("Felmeddelande! " + e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        lblUtbildning = new javax.swing.JLabel();
        lblForskning = new javax.swing.JLabel();
        cbxUtbildning = new javax.swing.JComboBox<>();
        cbxForskning = new javax.swing.JComboBox<>();
        btnTillbaka = new javax.swing.JButton();
        btnRadera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRubrik.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblRubrik.setText("Mina Projekt");

        lblUtbildning.setText("Mina utbildningsprojekt:");

        lblForskning.setText("Mina forskningsprojekt:");

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnRadera.setText("Radera projekt");
        btnRadera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaderaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTillbaka)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRadera, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblForskning, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxForskning, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUtbildning, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxUtbildning, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxUtbildning, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUtbildning, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblForskning, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxForskning, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(btnRadera, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTillbaka)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        this.dispose();
        new AnvStartsida(epost).setVisible(true);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnRaderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaderaActionPerformed
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        PreparedStatement ps = null;

        try {

            String utbildningsTitel = cbxUtbildning.getSelectedItem().toString();
            String forskningsTitel = cbxForskning.getSelectedItem().toString();

            if (utbildningsTitel != null && forskningsTitel.equals("")) {

                String sql = "DELETE FROM UTBILDNINGSPROJEKT WHERE TITEL = '" + utbildningsTitel + "'";
                ps = connection.prepareStatement(sql);
                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Projektet har raderats!");
                
            } else if (forskningsTitel != null && utbildningsTitel.equals("")) {
                String sql2 = "DELETE FROM FORSKNINGSPROJEKT WHERE TITEL = '" + forskningsTitel + "'";
                ps = connection.prepareStatement(sql2);
                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Projektet har raderats!");

            } else if (utbildningsTitel != null && forskningsTitel != null) {
                JOptionPane.showMessageDialog(null, "Välj endast ett projekt!");
            }

        } catch (Exception e) {
            System.out.println("Något gick fel!" + e);
        }
    }//GEN-LAST:event_btnRaderaActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRadera;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbxForskning;
    private javax.swing.JComboBox<String> cbxUtbildning;
    private javax.swing.JLabel lblForskning;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblUtbildning;
    // End of variables declaration//GEN-END:variables
}
