
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jenni
 */
public class MinaInlagg extends javax.swing.JFrame {
    
    String epost;

    /**
     * Creates new form MinaInlagg
     */
    public MinaInlagg() {
        initComponents();
        this.setLocationRelativeTo(null);
        fyllCbxFormella();
        fyllCbxInformella();
        txaHeltInlagg.setEditable(false);
    }
    
    public MinaInlagg(String e){
        epost = e;
        initComponents();
        this.setLocationRelativeTo(null);
        fyllCbxFormella();
        fyllCbxInformella();
        txaHeltInlagg.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        lblValjFormell = new javax.swing.JLabel();
        btnVisaHeltInlagg = new javax.swing.JButton();
        btnRaderaInlagg = new javax.swing.JButton();
        txaHeltInlagg = new java.awt.TextArea();
        btnTillbaka = new javax.swing.JButton();
        lblValjInformell = new javax.swing.JLabel();
        cbxInformella = new javax.swing.JComboBox<>();
        cbxFormella = new javax.swing.JComboBox<>();
        btnRedigeraFormella = new javax.swing.JButton();
        btnRedigeraInformella = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRubrik.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblRubrik.setText("Alla mina blogginlägg");

        lblValjFormell.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblValjFormell.setText("Visa rubriker (formella inlägg) :");

        btnVisaHeltInlagg.setText("Visa hela inlägget");
        btnVisaHeltInlagg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaHeltInlaggActionPerformed(evt);
            }
        });

        btnRaderaInlagg.setText("Radera inlägg");
        btnRaderaInlagg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaderaInlaggActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        lblValjInformell.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblValjInformell.setText("Visa rubriker (informella inlägg):");

        btnRedigeraFormella.setText("Redigera formellt inlägg");
        btnRedigeraFormella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedigeraFormellaActionPerformed(evt);
            }
        });

        btnRedigeraInformella.setText("Redigera informellt inlägg");
        btnRedigeraInformella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedigeraInformellaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnVisaHeltInlagg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRedigeraFormella)
                        .addGap(18, 18, 18)
                        .addComponent(btnRedigeraInformella)
                        .addGap(18, 18, 18)
                        .addComponent(btnRaderaInlagg)
                        .addGap(0, 73, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTillbaka))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblValjFormell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblValjInformell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxInformella, 0, 225, Short.MAX_VALUE)
                                    .addComponent(cbxFormella, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(txaHeltInlagg, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValjFormell, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(cbxFormella, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValjInformell)
                    .addComponent(cbxInformella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisaHeltInlagg)
                    .addComponent(btnRaderaInlagg)
                    .addComponent(btnRedigeraFormella)
                    .addComponent(btnRedigeraInformella))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txaHeltInlagg, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnTillbaka)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        this.dispose();
        new AnvStartsida(epost).setVisible(true);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    
    private void btnVisaHeltInlaggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaHeltInlaggActionPerformed
          DB_connection.DB_Connection obj_DB_Connection= new DB_connection.DB_Connection();
	  Connection connection=obj_DB_Connection.get_connection();
	  PreparedStatement ps=null;
          String inlagg = null;
          txaHeltInlagg.setText("");
          
          try {
              String formellRubrik = cbxFormella.getSelectedItem().toString();
              String informellRubrik = cbxInformella.getSelectedItem().toString();
 

              if(formellRubrik != null && informellRubrik.equals("")){
                  String sql = "SELECT TEXT FROM FORMELL_BLOGG WHERE RUBRIK = '" + formellRubrik +"'";
                  ps = connection.prepareStatement(sql);
                  ResultSet rs3 = ps.executeQuery();
                  
                  while(rs3.next()) {
                  inlagg = rs3.getString(1);
                  txaHeltInlagg.setText(inlagg);
                  }

              }
              
             else if(informellRubrik != null && formellRubrik.equals("")) {
                  String sql2 = "SELECT TEXT FROM INFORMELL_BLOGG WHERE RUBRIK = '" + informellRubrik +"'";
                  ps = connection.prepareStatement(sql2);
                  ResultSet rs = ps.executeQuery();
                  
                  while(rs.next()) {
                  inlagg = rs.getString(1);
                  txaHeltInlagg.setText(inlagg);
                  }
              }
              
              else if(formellRubrik != null && informellRubrik != null) {
                  JOptionPane.showMessageDialog(null, "Välj endast en rubrik!");
              }
              
              else {
                  JOptionPane.showMessageDialog(null, "Välj en rubrik!");
              }
          }
          catch(Exception e){
              System.out.println("Något gick fel!" + e);
          }
          
          
    }//GEN-LAST:event_btnVisaHeltInlaggActionPerformed

    private void btnRedigeraFormellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedigeraFormellaActionPerformed
        this.dispose();
        new RedigeraFormelltInlagg().setVisible(true);
    }//GEN-LAST:event_btnRedigeraFormellaActionPerformed

    private void btnRedigeraInformellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedigeraInformellaActionPerformed
        this.dispose();
        new RedigeraInformelltInlagg().setVisible(true);
    }//GEN-LAST:event_btnRedigeraInformellaActionPerformed

    private void btnRaderaInlaggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaderaInlaggActionPerformed
        DB_connection.DB_Connection obj_DB_Connection= new DB_connection.DB_Connection();
	  Connection connection=obj_DB_Connection.get_connection();
	  PreparedStatement ps=null;
          
          
          try{
              
              String formellRubrik = cbxFormella.getSelectedItem().toString();
              String informellRubrik = cbxInformella.getSelectedItem().toString();
              
              if(formellRubrik != null && informellRubrik.equals("")){
                  
                  String sql = "DELETE FROM FORMELL_BLOGG WHERE RUBRIK = '" + formellRubrik +"'";
                  ps = connection.prepareStatement(sql);
                  ps.executeUpdate();
                
                  JOptionPane.showMessageDialog(null, "Inlägget har raderats!");
              }
             
              
             else if(informellRubrik != null && formellRubrik.equals("")) {
                  String sql2 = "DELETE FROM INFORMELL_BLOGG WHERE RUBRIK = '" + informellRubrik +"'";
                  ps = connection.prepareStatement(sql2);
                  ps.executeUpdate();
                  
                  JOptionPane.showMessageDialog(null, "Inlägget har raderats!");
                 
              }
              
              else if(formellRubrik != null && informellRubrik != null) {
                  JOptionPane.showMessageDialog(null, "Välj endast en rubrik!");
              }
              
          }
              
          
          catch(Exception e) {
              System.out.println("Något gick fel!" + e);
          }
          
    }//GEN-LAST:event_btnRaderaInlaggActionPerformed
 private void fyllCbxFormella() {
     
     DB_connection.DB_Connection obj_DB_Connection= new DB_connection.DB_Connection();
	  Connection connection=obj_DB_Connection.get_connection();
	  PreparedStatement ps=null;
          String inlagg = null;
          cbxFormella.addItem("");
          
         try{
           String sql = "SELECT RUBRIK FROM FORMELL_BLOGG JOIN ANVANDARE ON FORMELL_BLOGG.ANVANDARID = ANVANDARE.ANVANDARID WHERE ANVANDARE.ANVANDARID = 1" ;
           ps = connection.prepareStatement(sql);
           ResultSet rs = ps.executeQuery();
           
           while(rs.next()){
               inlagg = rs.getString(1);
               cbxFormella.addItem(inlagg);
           } 
        }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, "Ett fel uppstod!");
         }  
    }
 
 private void fyllCbxInformella() {
     DB_connection.DB_Connection obj_DB_Connection= new DB_connection.DB_Connection();
	  Connection connection=obj_DB_Connection.get_connection();
	  PreparedStatement ps=null;
          String inlagg = null;
          cbxInformella.addItem("");
          
         try{
           String sql = "SELECT RUBRIK FROM INFORMELL_BLOGG JOIN ANVANDARE ON INFORMELL_BLOGG.ANVANDARID = ANVANDARE.ANVANDARID WHERE ANVANDARE.ANVANDARID = 1" ;
           ps = connection.prepareStatement(sql);
           ResultSet rs = ps.executeQuery();
           
           while(rs.next()){
               inlagg = rs.getString(1);
               cbxInformella.addItem(inlagg);
           } 
        }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, "Ett fel uppstod!");
         }  
    }
 
 
     
 
     
 
    
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRaderaInlagg;
    private javax.swing.JButton btnRedigeraFormella;
    private javax.swing.JButton btnRedigeraInformella;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JButton btnVisaHeltInlagg;
    private javax.swing.JComboBox<String> cbxFormella;
    private javax.swing.JComboBox<String> cbxInformella;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblValjFormell;
    private javax.swing.JLabel lblValjInformell;
    private java.awt.TextArea txaHeltInlagg;
    // End of variables declaration//GEN-END:variables
}

