
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jenni
 */
public class MinaInlagg extends javax.swing.JFrame {

    /**
     * Creates new form MinaInlagg
     */
    public MinaInlagg() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        btnVisaFormella = new javax.swing.JButton();
        btnVisaInformella = new javax.swing.JButton();
        cbxInlagg = new javax.swing.JComboBox<>();
        lblValjInlagg = new javax.swing.JLabel();
        btnVisaHeltInlagg = new javax.swing.JButton();
        btnRedigeraInlagg = new javax.swing.JButton();
        btnRaderaInlagg = new javax.swing.JButton();
        txaHeltInlagg = new java.awt.TextArea();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRubrik.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblRubrik.setText("Alla mina blogginlägg");

        btnVisaFormella.setText("Visa formella inlägg");
        btnVisaFormella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaFormellaActionPerformed(evt);
            }
        });

        btnVisaInformella.setText("Visa informella inlägg");
        btnVisaInformella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaInformellaActionPerformed(evt);
            }
        });

        lblValjInlagg.setText("Välj inlägg:");

        btnVisaHeltInlagg.setText("Visa hela inlägget");
        btnVisaHeltInlagg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaHeltInlaggActionPerformed(evt);
            }
        });

        btnRedigeraInlagg.setText("Redigera inlägg");

        btnRaderaInlagg.setText("Radera inlägg");

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnVisaFormella)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVisaInformella))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnVisaHeltInlagg)
                                    .addComponent(lblValjInlagg, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRedigeraInlagg)
                                        .addGap(30, 30, 30)
                                        .addComponent(btnRaderaInlagg))
                                    .addComponent(cbxInlagg, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(85, 85, 85))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnTillbaka)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txaHeltInlagg, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisaFormella)
                    .addComponent(btnVisaInformella))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValjInlagg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxInlagg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisaHeltInlagg)
                    .addComponent(btnRedigeraInlagg)
                    .addComponent(btnRaderaInlagg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(txaHeltInlagg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnTillbaka)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        this.dispose();
        new AnvStartsida().setVisible(true);
    }//GEN-LAST:event_btnTillbakaActionPerformed

//    public String GetQuery(String s) {
//        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
//        Connection connection = obj_DB_Connection.get_connection();
//        PreparedStatement ps = null;
//
//        String anvandarID = null;
//
//        try {
//            String query = s;
//            ps = connection.prepareStatement(query);
//            ResultSet rs = ps.executeQuery();
//
//            while (rs.next()) {
//                anvandarID = rs.getString(4);
//
//                String anvandare = hamtaAnvandare(anvandarID);
//
//                String resultat = "";
//            }
//        } catch (Exception e) {
//            System.out.println(e);
//        }
//        return ;
//    }
//
//    public String hamtaAnvandare(String id) {
//        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
//        Connection connection = obj_DB_Connection.get_connection();
//        PreparedStatement ps = null;
//        try {
//            String query = "select * from ANVANDARE where ANVANDARID = " + id;
//            ps = connection.prepareStatement(query);
//            ResultSet rs = ps.executeQuery();
//            while (rs.next()) {
//                anvandare = rs.getString(1);
//            }
//        } catch (Exception e) {
//            System.out.println(e);
//        }
//        return ;
//    }
    
    private void btnVisaInformellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaInformellaActionPerformed
          DB_connection.DB_Connection obj_DB_Connection= new DB_connection.DB_Connection();
	  Connection connection=obj_DB_Connection.get_connection();
	  PreparedStatement ps=null;
          String inlagg = null;
          
         try{
           String sql = "SELECT RUBRIK FROM INFORMELL_BLOGG JOIN ANVANDARE ON INFORMELL_BLOGG.ANVANDARID = ANVANDARE.ANVANDARID WHERE ANVANDARE.ANVANDARID = 1" ;
           ps = connection.prepareStatement(sql);
           ResultSet rs = ps.executeQuery();
           
           while(rs.next()){
               inlagg = rs.getString(1);
               cbxInlagg.addItem(inlagg);
           } 
        }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, "Ett fel uppstod!");
         }  
    }//GEN-LAST:event_btnVisaInformellaActionPerformed

    
    private void btnVisaHeltInlaggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaHeltInlaggActionPerformed
          DB_connection.DB_Connection obj_DB_Connection= new DB_connection.DB_Connection();
	  Connection connection=obj_DB_Connection.get_connection();
	  PreparedStatement ps=null;
          String inlagg = null;
          
          try{
              String rubrik = cbxInlagg.getSelectedItem().toString();
              
              String sql = "SELECT * FROM INFORMELL_BLOGG WHERE RUBRIK = " + rubrik + ";";
              ps = connection.prepareStatement(sql);
              ResultSet rs = ps.executeQuery();
              String informell = rs.getString(1);
           
//              String sql2 = "SELECT * FROM FORMELL_BLOGG WHERE RUBRIK = " + rubrik + ";";
//              ps = connection.prepareStatement(sql2);
//              ResultSet rs2 = ps.executeQuery();
//           
              if(informell != null){
                  String sql3 = "SELECT TEXT FROM INFORMELL_BLOGG WHERE RUBRIK = " + rubrik + ";";
                  ps = connection.prepareStatement(sql);
                  ResultSet rs3 = ps.executeQuery();
                  inlagg = rs3.getString(2);
                  txaHeltInlagg.setText(inlagg);
              }
              
          }
          catch(Exception e){
              System.out.println("Något gick fel!" + e);
          }
    }//GEN-LAST:event_btnVisaHeltInlaggActionPerformed

    
    private void btnVisaFormellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaFormellaActionPerformed
          DB_connection.DB_Connection obj_DB_Connection= new DB_connection.DB_Connection();
	  Connection connection=obj_DB_Connection.get_connection();
	  PreparedStatement ps=null;
          String inlagg = null;
          
         try{
           String sql = "SELECT RUBRIK FROM FORMELL_BLOGG JOIN ANVANDARE ON INFORMELL_BLOGG.ANVANDARID = ANVANDARE.ANVANDARID WHERE ANVANDARE.ANVANDARID = 1" ;
           ps = connection.prepareStatement(sql);
           ResultSet rs = ps.executeQuery();
           
           while(rs.next()){
               inlagg = rs.getString(1);
               cbxInlagg.addItem(inlagg);
           } 
        }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, "Ett fel uppstod!");
         }  
    }//GEN-LAST:event_btnVisaFormellaActionPerformed

    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRaderaInlagg;
    private javax.swing.JButton btnRedigeraInlagg;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JButton btnVisaFormella;
    private javax.swing.JButton btnVisaHeltInlagg;
    private javax.swing.JButton btnVisaInformella;
    private javax.swing.JComboBox<String> cbxInlagg;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblValjInlagg;
    private java.awt.TextArea txaHeltInlagg;
    // End of variables declaration//GEN-END:variables
}
