
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jenni
 */
public class UtbildningsProjekt extends javax.swing.JFrame {

    private String epost;
    private String id;
    public String filepath;
    private byte[] filebytes;
    /**
     * Creates new form UtbildningsProjekt
     */
    public UtbildningsProjekt(String e) {
        initComponents();
        this.setLocationRelativeTo(null);
        epost = e;
        id = getId();
        fillBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        btnSkapaProjekt = new javax.swing.JButton();
        cbxProjekt = new javax.swing.JComboBox<>();
        lblProjekt = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();
        btnMinaProjekt = new javax.swing.JButton();
        btnVisaProjekt = new javax.swing.JButton();
        jPanelBakgrund = new javax.swing.JPanel();
        lblSkrivInlagg = new javax.swing.JLabel();
        lblSkrivRubrik = new javax.swing.JLabel();
        lblSkrivText = new javax.swing.JLabel();
        txfRubrik = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaText = new javax.swing.JTextArea();
        lblSkrivFil = new javax.swing.JLabel();
        btnPosta = new javax.swing.JButton();
        txfFil = new javax.swing.JTextField();
        btnValjFil = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblInlagg = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtInlagg = new javax.swing.JTextArea();
        lblInlaggRubrik = new javax.swing.JLabel();
        lblForfattare = new javax.swing.JLabel();
        lblTidpunkt = new javax.swing.JLabel();
        txtSokvag = new javax.swing.JTextField();
        btnOppnaFil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRubrik.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        lblRubrik.setText("Utbildningsprojekt");

        btnSkapaProjekt.setText("Skapa nytt projekt");
        btnSkapaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkapaProjektActionPerformed(evt);
            }
        });

        cbxProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProjektActionPerformed(evt);
            }
        });

        lblProjekt.setText("Projekt jag har åtkomst till:");

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnMinaProjekt.setText("Mina projekt");
        btnMinaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinaProjektActionPerformed(evt);
            }
        });

        btnVisaProjekt.setText("Visa");
        btnVisaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaProjektActionPerformed(evt);
            }
        });

        jPanelBakgrund.setBackground(new java.awt.Color(153, 153, 153));

        lblSkrivInlagg.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblSkrivInlagg.setText("Skriv ett inlägg i projektet!");

        lblSkrivRubrik.setText("Rubrik:");

        lblSkrivText.setText("Text:");

        txfRubrik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfRubrikActionPerformed(evt);
            }
        });

        txaText.setColumns(20);
        txaText.setRows(5);
        jScrollPane1.setViewportView(txaText);

        lblSkrivFil.setText("Ladda upp fil:");

        btnPosta.setText("Publicera");
        btnPosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostaActionPerformed(evt);
            }
        });

        btnValjFil.setText("Välj");
        btnValjFil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValjFilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBakgrundLayout = new javax.swing.GroupLayout(jPanelBakgrund);
        jPanelBakgrund.setLayout(jPanelBakgrundLayout);
        jPanelBakgrundLayout.setHorizontalGroup(
            jPanelBakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBakgrundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBakgrundLayout.createSequentialGroup()
                        .addGroup(jPanelBakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelBakgrundLayout.createSequentialGroup()
                                .addComponent(lblSkrivFil, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfFil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnValjFil))
                            .addGroup(jPanelBakgrundLayout.createSequentialGroup()
                                .addGroup(jPanelBakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblSkrivRubrik, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                    .addComponent(lblSkrivText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelBakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                    .addComponent(txfRubrik))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBakgrundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblSkrivInlagg)
                        .addGap(114, 114, 114))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBakgrundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPosta, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        jPanelBakgrundLayout.setVerticalGroup(
            jPanelBakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBakgrundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSkrivInlagg, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanelBakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSkrivRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSkrivText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnValjFil)
                    .addGroup(jPanelBakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSkrivFil, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txfFil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnPosta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tblInlagg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rubrik", "Författare"
            }
        ));
        tblInlagg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInlaggMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblInlagg);

        txtInlagg.setColumns(20);
        txtInlagg.setRows(5);
        jScrollPane4.setViewportView(txtInlagg);

        btnOppnaFil.setText("Öppna");
        btnOppnaFil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOppnaFilActionPerformed(evt);
            }
        });

        jLabel2.setText("Välj ett inlägg att visa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblForfattare, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(lblTidpunkt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtSokvag)
                                .addGap(18, 18, 18)
                                .addComponent(btnOppnaFil, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblInlaggRubrik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 35, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblProjekt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnVisaProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanelBakgrund, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap())))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnMinaProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSkapaProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(95, 95, 95))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInlaggRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblForfattare, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTidpunkt, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSokvag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOppnaFil))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVisaProjekt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelBakgrund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMinaProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(btnSkapaProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaProjektActionPerformed
        this.dispose();
        new MinaProjekt(epost,id,true).setVisible(true);
    }//GEN-LAST:event_btnMinaProjektActionPerformed

    private void btnSkapaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkapaProjektActionPerformed
        this.dispose();
        new SkapaNyttUtbildningsProjekt(epost).setVisible(true);
    }//GEN-LAST:event_btnSkapaProjektActionPerformed

    private void cbxProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProjektActionPerformed
        //nah
    }//GEN-LAST:event_cbxProjektActionPerformed

    public String GetQuery(String s)
    {
	DB_connection.DB_Connection obj_DB_Connection= new DB_connection.DB_Connection();
	Connection connection=obj_DB_Connection.get_connection();
	PreparedStatement ps=null;
        String rubrik = null;
        String fornamn = null;
        String efternamn = null;
        
        DefaultTableModel tabellen = (DefaultTableModel)tblInlagg.getModel();
        int rowCount = tabellen.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            tabellen.removeRow(i);
        }
        
	try {
	    String query= s;
	    ps=connection.prepareStatement(query);
	    ResultSet rs=ps.executeQuery();
	    while(rs.next()){
                rubrik = rs.getString(2);
                fornamn = rs.getString(10);
                efternamn = rs.getString(11);
                
                String forfattare = fornamn + " " + efternamn;
                                                
                DefaultTableModel tabellen1 = (DefaultTableModel) tblInlagg.getModel();
                tabellen1.addRow(new Object[]{rubrik,forfattare});
                
                
	    }
	} catch (Exception e) {
	    System.out.println(e);
	} 
        return rubrik;
    }
    private void btnVisaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaProjektActionPerformed
        String rubrik = cbxProjekt.getSelectedItem().toString();
        
        
            try
            {
            
            String fraga= "SELECT * FROM UTBILDNINGSINLAGG JOIN ANVANDARE ON ANVANDARE.ANVANDARID = UTBILDNINGSINLAGG.ANVANDARID JOIN UTBILDNINGSPROJEKT ON UTBILDNINGSINLAGG.UPID = UTBILDNINGSPROJEKT.UPID WHERE UTBILDNINGSPROJEKT.TITEL = '" + rubrik + "' ORDER BY TIDPUNKT DESC";
                
                
            String hemta = GetQuery(fraga);
                
                
            }
            catch (Exception bla)
            {
             JOptionPane.showMessageDialog(null, "Något gick fel!");
            }
            
        lblInlaggRubrik.setText("");
        txtInlagg.setText("");
        lblForfattare.setText("");
        lblTidpunkt.setText("");    
    }//GEN-LAST:event_btnVisaProjektActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        this.dispose();
        new AnvStartsida(epost).setVisible(true);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnPostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostaActionPerformed
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        PreparedStatement ps = null;
        if (Validering.textFaltHarVarde(txfRubrik) && Validering.textAreaHarVarde(txaText))
        {
            try
            {
            String sokväg = null;
            byte[] fileBytes = null;
                    
                    if (txfFil.getText().isEmpty()) 
                    {
                        //String sokväg = null;
                    }
                    else
                    {
                        sokväg = txfFil.getText();
                        Path path = Paths.get(sokväg);
                        fileBytes = Files.readAllBytes(path);
                        sokväg = path.getFileName().toString();
                    }
    
                
            //String sokväg = txfFil.getText();
            //Path path = Paths.get(sokväg);
            //byte[] fileBytes = Files.readAllBytes(path);
            
            String rubrik = txfRubrik.getText();
            String text = txaText.getText();
            String uiid = GetAutoId("SELECT MAX(UIID) FROM UTBILDNINGSINLAGG");
            String tidpunkt = hemtaTidpunkt();
            String personId = getId();
            String upid = getUpid();
            
            //sokväg = path.getFileName().toString();
            
//            String query = "INSERT INTO FORSKNINGSINLAGG VALUES ("+fiid+",'"+rubrik+"','"+text+"','"sokväg"','"+tidpunkt+"',"+personId+","+fpid+","fileBytes")";
            String query = "insert into UTBILDNINGSINLAGG (UIID, RUBRIK, TEXT, FIL, TIDPUNKT, ANVANDARID, UPID, NYFIL) values"
                        + " (?, ?, ?, ?, ?, ?, ?, ?)";
                ps = connection.prepareStatement(query);
                ps.setString(1, uiid);
                ps.setString(2, rubrik);
                ps.setString(3, text);                         
                ps.setString(4, sokväg);
                ps.setString(5, tidpunkt);
                ps.setString(6, personId);
                ps.setString(7, upid);
                ps.setBytes(8, fileBytes); 
                ps.execute();
            updateSql(query);
            JOptionPane.showMessageDialog(null, "Inlägget har publicerats!");
            txfRubrik.setText(null);
            txaText.setText(null);
            txfFil.setText(null);
            
        }
            
       catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_btnPostaActionPerformed

    private void txfRubrikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfRubrikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfRubrikActionPerformed

    private void btnValjFilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValjFilActionPerformed
        // TODO add your handling code here:      JFileChooser jfc = new JFileChooser();
      JFileChooser jfc = new JFileChooser();
      jfc.showOpenDialog(this);
      
      try {
                  File f = jfc.getSelectedFile();
                  filepath = f.getAbsolutePath();
                  filepath = filepath.replace('\\', '/');
                  txfFil.setText(filepath);
//                  Path path = Paths.get(filepath);
//                  byte[] fileBytes = Files.readAllBytes(path);
      }
      catch (Exception e)
      {
          JOptionPane.showMessageDialog(rootPane, e);
      }
    }//GEN-LAST:event_btnValjFilActionPerformed

    private void tblInlaggMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInlaggMouseClicked

        DefaultTableModel tabellen = (DefaultTableModel)tblInlagg.getModel();
        int selectedRowIndex = tblInlagg.getSelectedRow();

        String id = (tabellen.getValueAt(selectedRowIndex, 0).toString());
        

        //id är rubrik nu dock

        String fraga= "SELECT * FROM UTBILDNINGSINLAGG WHERE RUBRIK = '" + id + "'";

        String text = GetText(fraga);

    }//GEN-LAST:event_tblInlaggMouseClicked

    private void btnOppnaFilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOppnaFilActionPerformed
        // TODO add your handling code here:
                        filepath = txtSokvag.getText();
        try {
            
           String basepath = System.getProperty("user.dir");
           String newfilepath = basepath + "\\src\\UploadedFiles\\" + filepath; 
           Path path = Paths.get(newfilepath);
           if (Files.exists(path))
                   {
                       Files.delete(path);
                   }
           File file = new File(newfilepath);
           FileOutputStream os = new FileOutputStream(file); 
           
           os.write(filebytes);
           os.close();
            
            File pdfFile = new File(newfilepath);
            if (pdfFile.exists())
            {
                if (Desktop.isDesktopSupported())
                {
                    Desktop.getDesktop().open(pdfFile);
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "desktop is not supported");
                }
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "File doesnt exist");
            }
        }
        catch ( HeadlessException | IOException e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnOppnaFilActionPerformed
public String GetText(String s)
    {
	DB_connection.DB_Connection obj_DB_Connection= new DB_connection.DB_Connection();
	Connection connection=obj_DB_Connection.get_connection();
	PreparedStatement ps=null;
        String rubrik = null;
        String text = null;
        String tidpunkt = null;
        String fil = null;
        

	try {
	    String query= s;
	    ps=connection.prepareStatement(query);
	    ResultSet rs=ps.executeQuery();
	    while(rs.next()){
                rubrik = rs.getString(2);
                text = rs.getString(3);
                tidpunkt = rs.getString(5);
                fil = rs.getString(4);
                filebytes = rs.getBytes(8);
                
	    }
            DefaultTableModel tabellen = (DefaultTableModel)tblInlagg.getModel();
            int selectedRowIndex = tblInlagg.getSelectedRow();
            
            String namn = "Av: " + (tabellen.getValueAt(selectedRowIndex, 1).toString());
            
            String tid = tidpunkt.substring(0, 16);
            
            lblInlaggRubrik.setText(rubrik);
            txtInlagg.setText(text);    
            lblForfattare.setText(namn);            
            lblTidpunkt.setText(tid);
            txtSokvag.setText(fil);
            
            
	} catch (Exception e) {
	    System.out.println(e);
	}         
        
        return text;
    }
    
    private String getId(){
        String id1 = null;
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        try {
            String query = "SELECT ANVANDARID FROM ANVANDARE WHERE EPOST='"+epost+"'";
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                id1 = rs.getString(1);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return id1;
    }
    
    private void fillBox(){
        cbxProjekt.removeAllItems();
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        try {
            String query = "SELECT TITEL FROM ANVANDARE_UTBILDNINGSPROJEKT JOIN UTBILDNINGSPROJEKT ON ANVANDARE_UTBILDNINGSPROJEKT.UPID=UTBILDNINGSPROJEKT.UPID WHERE ANVANDARE_UTBILDNINGSPROJEKT.ANVANDARID="+id;
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                cbxProjekt.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    public String GetAutoId(String o) {
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        int idNy = 1;
        try {
            String query = o;
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                idNy = rs.getInt(1);
            }

        } catch (Exception ex) {
            System.out.println("Internt felmeddelande: " + ex);
        }

        idNy = idNy + 1;

        return Integer.toString(idNy);

    }
    
    public String hemtaTidpunkt() {

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();

        return dtf.format(now);

    }
    
    public String getUpid(){
        int uPid = 0;
        String titel = cbxProjekt.getSelectedItem().toString();
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        try {
            PreparedStatement ps = connection.prepareStatement("SELECT UPID FROM UTBILDNINGSPROJEKT WHERE TITEL ='"+titel+"'");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                uPid = rs.getInt(1);

            }

        } catch (Exception ex) {
            System.out.println("Internt felmeddelande: " + ex);
        }
        
        return Integer.toString(uPid);
        
    }
    
        private void updateSql(String statement)
    {
        DB_connection.DB_Connection obj_DB_Connection = new DB_connection.DB_Connection();
        Connection connection = obj_DB_Connection.get_connection();
        try{
       PreparedStatement ps = connection.prepareStatement(statement);
       ps.executeUpdate();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMinaProjekt;
    private javax.swing.JButton btnOppnaFil;
    private javax.swing.JButton btnPosta;
    private javax.swing.JButton btnSkapaProjekt;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JButton btnValjFil;
    private javax.swing.JButton btnVisaProjekt;
    private javax.swing.JComboBox<String> cbxProjekt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelBakgrund;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblForfattare;
    private javax.swing.JLabel lblInlaggRubrik;
    private javax.swing.JLabel lblProjekt;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblSkrivFil;
    private javax.swing.JLabel lblSkrivInlagg;
    private javax.swing.JLabel lblSkrivRubrik;
    private javax.swing.JLabel lblSkrivText;
    private javax.swing.JLabel lblTidpunkt;
    private javax.swing.JTable tblInlagg;
    private javax.swing.JTextArea txaText;
    private javax.swing.JTextField txfFil;
    private javax.swing.JTextField txfRubrik;
    private javax.swing.JTextArea txtInlagg;
    private javax.swing.JTextField txtSokvag;
    // End of variables declaration//GEN-END:variables
}
